### ISSUE TITLE
Representation of numeric values as a range of characters

### ISSUE THREAD

**Issue by flying-sheep** [sardemff7/j4status#11]
Other similar projects allow to interpolate on a given list to display something.

What i mean is that given e.g. an interpolation list of `[" ", "▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"]`, one can interpolate a numeric value (e.g. between 0 and 100, or 0 and 1) on this list.

This could be used in formatting or for labels (if used for labels, there has to be a concept of a “main number” that can be used for interpolation, e.g. hours÷12 for time, signal strength for wifi, volume, charge, …)

**Comment by sardemff7** [comment]
As promised, this feature now exists. It's not pushed yet but it's a matter of days, as the main code is working already.

**Comment by flying-sheep** [comment]
Very cool, thank you!

**Comment by sardemff7** [comment]
And here it is, commit e25d9a653f13802549ed2a5f356b812ad670f873! Enjoy :-)

**Comment by sardemff7** [comment]
FTR: the syntax is `${signal:[;0;100; ;▁;▂;▃;▄;▅;▆;▇;█]}`
