### ISSUE TITLE
Plugin initialization failure not verbose enough

### ISSUE THREAD

**Issue by goviedo** [sardemff7/j4status#12]
The plugins with -o flat and with the [plugins] in j4status/config sections doesnt work with git version. time works, upower works, systemd, but nm doesnt work, i3bar doesnt work.

I noticed that if NetworkManager is not running, j4status says not input plugin with no error specified, maybe the others doesnt work because fails finding the program o service.

**Comment by sardemff7** [comment]
Fixed for other plugins in 244130d23261b3e0d74ab8036e72c60c21b02fa5, 6919dd53f6e7e195275c1a8f5779d52e5381ab85, 1f64b4a8133f49b9fcae7bec56678fe6015d6231, 363b76126b0d137c3f47a831a045c3e83e29cf84, dd2e0a5677e4d48edc8eb5919d8a905c2a7dba59, 24c203ba65c8f3484d15d01b6feee424debebdff and 0c5b19c4d1844bbc1d6feed2f069324d8767b820.
