### ISSUE TITLE
Release for packaging

### ISSUE THREAD

**Issue by moritzheiber** [sardemff7/j4status#15]
So far I wasn't able to find a release package for j4status, would it be possible for you to provide a release tarball (i.e. a 0.0.1/0.1.0 version)?

It would make it easier to package j4status (for Debian/Ubuntu in my case).

Thanks!

**Comment by sardemff7** [comment]
0.1 release made.
You can either download the [bare Git source code](https://github.com/sardemff7/j4status/archive/v0.1.tar.gz) (needs Autotools to build) or the [pre-generated tarball](https://github.com/sardemff7/j4status/releases/download/v0.1/j4status-0.1.tar.xz).
