### ISSUE TITLE
Links in the README point to a domain sitter site

### ISSUE THREAD

**Issue by hukka** [sardemff7/j4status#23]
Seems like j4tools.org has been lost to domain sitters.

**Comment by sardemff7** [comment]
Fixed in 57848c895cbdf6516d3c57ca4073a22dc479a32b. Thanks

**Comment by hukka** [comment]
The screenshot png is still pointing to j4tools.org

**Comment by sardemff7** [comment]
Oh, my bad. Removed in c85cb95f5361f4cbb1b140bbc48f97d531def4fa. Thanks again :-)
