### ISSUE TITLE
Cannot build due to file “meson_options.txt” missing

### ISSUE THREAD

**Issue by aperezdc** [sardemff7/j4status#26]
As of 8c017e48443a81d48a2664b09c8f65c02c6a0d74 building from a checkout of the Git repository does not work because the `meson_options.txt` file is missing, and Meson complains about undefined options.

**Comment by sardemff7** [comment]
Oops, my bad. Fixed in bb240bf67b7b1c58ab68ab97c7ae4a965010e13c.
