### ISSUE TITLE
[REQUEST] Merge wip/evp branch on master

### ISSUE THREAD

**Issue by AhmedAA** [sardemff7/j4status#27]
Hi!

Thank you for this tool.
I used it previously to replace i3bar completely and use it with eventd to spawn notifications.

Unfortunately it seems that it has been abandoned :(

Any change it can be merged with master?

Appreciate it!

**Comment by sardemff7** [comment]
Pushed as 2597742f0c09592facdb70ed64619911173e5242. Though I don’t feel it’s as polished as the other plugins. Specifically it could use a nicer value handling (with strong types instead of just strings).

**Comment by sardemff7** [comment]
But I’m surprised anyone still uses it. :-D

**Comment by AhmedAA** [comment]
> But I’m surprised anyone still uses it. :-D

It is an awesome alternative to having bars :)
And honestly I find bars distractive. This is much cleaner in terms of just getting the necessary information when you want!

Thank you :)
